//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Book
    {
        public Tbl_Book()
        {
            this.Tbl_Cart = new HashSet<Tbl_Cart>();
        }
    
        public int BookId { get; set; }
        public string BookName { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Description { get; set; }
        public string BookImage { get; set; }
        public Nullable<bool> IsFeatured { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> PublicationDate { get; set; }
    
        public virtual Tbl_Category Tbl_Category { get; set; }
        public virtual ICollection<Tbl_Cart> Tbl_Cart { get; set; }
    }
}
